import Footer from "./Components/UI/Footer";
import NavBar from "./Components/UI/NavBar";
import "./globals.css";

export const metadata = {
  title: "Meeras website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
