import Newsletter from "./Components/Newsletter";
import "../globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className=" bg-lightgreen">
      {children}
      <section className="pb-20">
        <Newsletter />
      </section>
    </main>
  );
}
